language: objective-c

before_install:
    - gem install slather
    - brew update
    - if brew outdated | grep -qx xctool; then brew upgrade xctool; fi
    - pod install

xcode_workspace: Snowplow.xcworkspace
xcode_scheme: Snowplow
xcode_sdk:
    - iphonesimulator

after_success: slather
